title: Civic Tech Toronto
author:
  name: Civic Tech Toronto
  email: hi@civictech.ca

description: >-
  Civic Tech Toronto is a vibrant and diverse community of Torontonians engaged 
  in understanding and creating solutions for civic challenges through technology, 
  design, and other innovative means.

baseurl: ""
github_username: civictechto

timezone: America/Toronto
future: true

include:
  - _pages
  - llms.txt

exclude:
  - Makefile
  - .obsidian
  - .gitignore
  - .gitmodules
  - .ruby-version
  - docs
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - archives/utilities
  - archives/data
  - archives/.gitignore
  - archives/LICENSE
  - archives/hacknights.base
  - archives/README.md

collections_dir: archives
collections:
  announcements:
    output: true
    sort_by: date
    permalink: /:collection/:path/
  meetups:
    output: true
    sort_by: date
    permalink: /events/:path/
  organizations:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/
  venues:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
      sort_by: date
  - scope:
      path: ""
      type: meetups
    values:
      layout: meetup
      sort_by: date
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
  - scope:
      path: ""
      type: people
    values:
      layout: person
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: venues
    values:
      layout: venue
  - scope:
      path: ""
      type: resources
    values:
      layout: resource

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll_picture_tag
  - jekyll-loading-lazy

# jekyll_picture_tag settings
picture:
  source: "archives/images"
  output: "assets/thumbs"
  ignore_missing_images: true

use_html_extension: false
